services:
  db:
    image: postgres:18
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    ports:
      - "15432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      # DATABASE_USER: postgres
      # DATABASE_PASSWORD: password
      # DATABASE_HOSTNAME: db
      DATABASE_NAME: rails_v8_1_2_react19_vite_development
      DATABASE_URL: postgres://postgres:password@db:5432/db
    volumes:
      - .:/app:cached
      - /node_modules
      - tmp-data:/app/tmp
      - log-data:/app/log
      - ./coverage:/app/coverage
    tty: true
    stdin_open: true
    depends_on:
      - db
    command: >-
      bash -c "rm -f tmp/pids/server.pid &&
      bundle config set --local path "vendor/bundle" &&
      bundle config set clean "true" &&
      npm install &&
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    dns:
      - 1.1.1.1

volumes:
  db-data:
    driver: local
  tmp-data:
  log-data:
