name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Clean bundle directory
        run: rm -rf vendor/bundle .bundle

      - name: Install libvips
        run: |
          sudo apt update
          sudo apt install -y libvips libvips-dev
          
          # システムにインストールされた本物の libvips.so パスを探す
          REAL_VIPS_SO=$(find /usr/lib -name "libvips.so.*" ! -type l | head -n 1)
          if [ -z "$REAL_VIPS_SO" ]; then
            REAL_VIPS_SO=$(find /usr/lib -name "libvips.so" | head -n 1)
          fi
          
          VIPS_DIR=$(dirname "$REAL_VIPS_SO")
          
          # Ruby（ruby-vips）が探しにいく可能性がある名前ですべてリンクを貼る
          sudo ln -sf "$REAL_VIPS_SO" "$VIPS_DIR/vips.so.42"
          sudo ln -sf "$REAL_VIPS_SO" "$VIPS_DIR/libvips.so.42"
          sudo ln -sf "$REAL_VIPS_SO" "/usr/local/lib/vips.so.42"
          sudo ln -sf "$REAL_VIPS_SO" "/usr/local/lib/libvips.so.42"
          
          # システム全体にライブラリのパスを強制的に再認識させる
          sudo ldconfig

      - name: Force ffi to compile from source
        run: |
          bundle config set --local force_ruby_platform true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
      
      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit
      
  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true

      - name: Prepare RuboCop cache
        uses: actions/cache@v5
        env:
          DEPENDENCIES_HASH: ${{ hashFiles('.ruby-version', '**/.rubocop.yml', '**/.rubocop_todo.yml', 'Gemfile.lock') }}
        with:
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          key: rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-${{ github.ref_name == github.event.repository.default_branch && github.run_id || 'default' }}
          restore-keys: |
            rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-

      - name: Lint code for consistent style
        run: bin/rubocop -f github
